// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvltuzbkfozsatboyqtv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2bHR1emJrZm96c2F0Ym95cXR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5Njc0NzgsImV4cCI6MjA3MTU0MzQ3OH0.PE08TdT1tl58IZt0Z13V7JTNflJR0WR5oC8JegSm9yg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});